image: Visual Studio 2017

init:
  - ps: Update-AppveyorBuild -Version '1.9.0-pre3pdb' + [int]::Parse($env:appveyor_build_number).ToString('000')

install:
  - git submodule update --init
  - pip install six
  - pip install httplib2
  - pip install google-api-python-client
  - choco install yasm
  - choco install ninja

build_script:
  - python tools/run_tests/run_tests.py -c dbg -l csharp --build_only --disable_auto_set_flakes
  - ps: |
      cd $env:appveyor_build_folder\src\csharp

      # use existing native libraries
      nuget install Grpc.Core -version 1.9.0-pre2
      $dir = "$pwd\Grpc.Core.1.9.0-pre2"
      # md nativelibs
      md nativelibs\csharp_ext_macos_x64
      cp $dir/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib nativelibs\csharp_ext_macos_x64\libgrpc_csharp_ext.dylib
      md nativelibs\csharp_ext_macos_x86
      cp $dir/runtimes/osx/native/libgrpc_csharp_ext.x86.dylib nativelibs\csharp_ext_macos_x86\libgrpc_csharp_ext.dylib
      md nativelibs\csharp_ext_linux_x64
      cp $dir/runtimes/linux/native/libgrpc_csharp_ext.x64.so nativelibs\csharp_ext_linux_x64\libgrpc_csharp_ext.so
      md nativelibs\csharp_ext_linux_x86
      cp $dir/runtimes/linux/native/libgrpc_csharp_ext.x86.so nativelibs\csharp_ext_linux_x86\libgrpc_csharp_ext.so
      md nativelibs\csharp_ext_windows_x64
      cp $dir/runtimes/win/native/grpc_csharp_ext.x64.dll nativelibs\csharp_ext_windows_x64\grpc_csharp_ext.dll
      md nativelibs\csharp_ext_windows_x86
      cp $dir/runtimes/win/native/grpc_csharp_ext.x86.dll nativelibs\csharp_ext_windows_x86\grpc_csharp_ext.dll

  - build_packages_dotnetcli.bat

test: off

artifacts:
  - path: artifacts\*.nupkg