image: Visual Studio 2017
install:
  - git submodule update --init
  - pip install six
  - pip install httplib2
  - pip install google-api-python-client
  - choco install yasm
  - choco install ninja
build_script:
  - python tools/run_tests/run_tests.py -c dbg -l csharp --build_only --disable_auto_set_flakes
test: off